### ISSUE TITLE
`--path` option doesn't work.

### ISSUE THREAD

**Issue by BlaCkinkGJ** [BlaCkinkGJ/catch-me-if-you-can#1]
The current version doesn't work well with the `-p` options. For example, I suppose that I have a `temp` directory which has `sample1, sample2, sample3` files.

In that case, I ran the program with `./plagiarism.py --path temp` command. And then we checked the returns, we found that the program only returns `sample1 sample2 sample3` which means it doesn't contain the `temp` directory information.

P.S. I attach the location of need fix lines.

https://github.com/BlaCkinkGJ/catch-me-if-you-can/blob/0ca046701a0400bc5a2f2828b58569ca1a69c3a4/plagiarism.py#L201

**Comment by fahmij8** [comment]
Excuse me, I believe your documentation doesn't clear enough to explain how to compare between files and reference files
There's only -t there..
Please explain more...

**Comment by BlaCkinkGJ** [comment]
I'm really sorry for not enough documentation to write related in implement of this project. I will add more info to README.md about the implementation of how to compare each file as soon as possible.

Thanks for your interest in my project.

Best regards,
BlaCkinkGJ

**Comment by fahmij8** [comment]
Sure, thank you in advance
Can't wait for the update!

**Comment by BlaCkinkGJ** [comment]
Sorry for being too late. I just added Please check it, and if you do not understand, please contact me and we will correct it. However, I close this issue. Because this issue is resolved.
